global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'demo-app-monitor'

scrape_configs:
  - job_name: 'demo-app'
    static_configs:
      - targets: ['app:8000']
        labels:
          service: 'demo-app'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'
    metric_relabel_configs:
      - source_labels: [container_label_app]
        target_label: app_name
        regex: '(.+)'
        replacement: '${1}'
      - source_labels: [container_label_service]
        target_label: service_name
        regex: '(.+)'
        replacement: '${1}'
      - source_labels: [container_label_component]
        target_label: component_name
        regex: '(.+)'
        replacement: '${1}'
      - source_labels: [container_label_app, container_label_service]
        target_label: container_identifier
        separator: '-'
        regex: '(.+)'
        replacement: '${1}'
